external_providers:
  - name: "Discord"
    url: "https://localhost:8000"
  # - url: "https://google-calendar-api.com/events"
  #   name: "Google Calendar"
  # - url: "https://slack-api.com/events"
  #   name: "Slack"
