external_providers:
  - url: "https://localhost:8000"
    name: "Discord"
  
  - url: "https://google-calendar-api.com/events"
    name: "Google Calendar"
  
  - url: "https://slack-api.com/events"
    name: "Slack"
