external_providers:
  - url: "https://discord-api.com/events"
    name: "Discord"
  
  - url: "https://google-calendar-api.com/events"
    name: "Google Calendar"
  
  - url: "https://slack-api.com/events"
    name: "Slack"
